package com.xh.sci.model.pojo;

import java.util.Date;

public class BizCourseSchedule extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.SCHEDULE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String scheduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.SCHEDULE_DATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Date scheduleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.WEEKDAY_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Integer weekdayId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Integer lessonIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.START_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.END_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.TEACHER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String teacherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.STUDENT_COURSE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String studentCourseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.STUDENT_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.COURSE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String courseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.DIVIDE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String divideId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.ORG_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.STATUS_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String statusId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.TYPE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.OLD_SCHEDULE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String oldScheduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.AUTO_SCHEDULE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String autoSchedule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.ORIGINAL_LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Integer originalLessonIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.TARGET_LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Integer targetLessonIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.IS_STOP
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String isStop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.IS_SIGN
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String isSign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.SIGN_DATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Date signDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.IS_AUTO_SIGN
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String isAutoSign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.ALLOW_TRANSFER
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String allowTransfer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.ALLOW_MULTI
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String allowMulti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.RECORD_STATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String recordState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.CREATE_USER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.CREATE_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.MODIFY_USER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private String modifyUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_course_schedule.MODIFY_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.SCHEDULE_ID
	 * @return  the value of biz_course_schedule.SCHEDULE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getScheduleId() {
		return scheduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.SCHEDULE_ID
	 * @param scheduleId  the value for biz_course_schedule.SCHEDULE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.SCHEDULE_DATE
	 * @return  the value of biz_course_schedule.SCHEDULE_DATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Date getScheduleDate() {
		return scheduleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.SCHEDULE_DATE
	 * @param scheduleDate  the value for biz_course_schedule.SCHEDULE_DATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setScheduleDate(Date scheduleDate) {
		this.scheduleDate = scheduleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.WEEKDAY_ID
	 * @return  the value of biz_course_schedule.WEEKDAY_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Integer getWeekdayId() {
		return weekdayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.WEEKDAY_ID
	 * @param weekdayId  the value for biz_course_schedule.WEEKDAY_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setWeekdayId(Integer weekdayId) {
		this.weekdayId = weekdayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.LESSON_INDEX
	 * @return  the value of biz_course_schedule.LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Integer getLessonIndex() {
		return lessonIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.LESSON_INDEX
	 * @param lessonIndex  the value for biz_course_schedule.LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setLessonIndex(Integer lessonIndex) {
		this.lessonIndex = lessonIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.START_TIME
	 * @return  the value of biz_course_schedule.START_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.START_TIME
	 * @param startTime  the value for biz_course_schedule.START_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.END_TIME
	 * @return  the value of biz_course_schedule.END_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.END_TIME
	 * @param endTime  the value for biz_course_schedule.END_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.TEACHER_ID
	 * @return  the value of biz_course_schedule.TEACHER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.TEACHER_ID
	 * @param teacherId  the value for biz_course_schedule.TEACHER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.STUDENT_COURSE_ID
	 * @return  the value of biz_course_schedule.STUDENT_COURSE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getStudentCourseId() {
		return studentCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.STUDENT_COURSE_ID
	 * @param studentCourseId  the value for biz_course_schedule.STUDENT_COURSE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setStudentCourseId(String studentCourseId) {
		this.studentCourseId = studentCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.STUDENT_ID
	 * @return  the value of biz_course_schedule.STUDENT_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.STUDENT_ID
	 * @param studentId  the value for biz_course_schedule.STUDENT_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.COURSE_ID
	 * @return  the value of biz_course_schedule.COURSE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.COURSE_ID
	 * @param courseId  the value for biz_course_schedule.COURSE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.DIVIDE_ID
	 * @return  the value of biz_course_schedule.DIVIDE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getDivideId() {
		return divideId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.DIVIDE_ID
	 * @param divideId  the value for biz_course_schedule.DIVIDE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setDivideId(String divideId) {
		this.divideId = divideId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.ORG_ID
	 * @return  the value of biz_course_schedule.ORG_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.ORG_ID
	 * @param orgId  the value for biz_course_schedule.ORG_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.STATUS_ID
	 * @return  the value of biz_course_schedule.STATUS_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.STATUS_ID
	 * @param statusId  the value for biz_course_schedule.STATUS_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.TYPE_ID
	 * @return  the value of biz_course_schedule.TYPE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.TYPE_ID
	 * @param typeId  the value for biz_course_schedule.TYPE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.OLD_SCHEDULE_ID
	 * @return  the value of biz_course_schedule.OLD_SCHEDULE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getOldScheduleId() {
		return oldScheduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.OLD_SCHEDULE_ID
	 * @param oldScheduleId  the value for biz_course_schedule.OLD_SCHEDULE_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setOldScheduleId(String oldScheduleId) {
		this.oldScheduleId = oldScheduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.AUTO_SCHEDULE
	 * @return  the value of biz_course_schedule.AUTO_SCHEDULE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getAutoSchedule() {
		return autoSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.AUTO_SCHEDULE
	 * @param autoSchedule  the value for biz_course_schedule.AUTO_SCHEDULE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setAutoSchedule(String autoSchedule) {
		this.autoSchedule = autoSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.ORIGINAL_LESSON_INDEX
	 * @return  the value of biz_course_schedule.ORIGINAL_LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Integer getOriginalLessonIndex() {
		return originalLessonIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.ORIGINAL_LESSON_INDEX
	 * @param originalLessonIndex  the value for biz_course_schedule.ORIGINAL_LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setOriginalLessonIndex(Integer originalLessonIndex) {
		this.originalLessonIndex = originalLessonIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.TARGET_LESSON_INDEX
	 * @return  the value of biz_course_schedule.TARGET_LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Integer getTargetLessonIndex() {
		return targetLessonIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.TARGET_LESSON_INDEX
	 * @param targetLessonIndex  the value for biz_course_schedule.TARGET_LESSON_INDEX
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setTargetLessonIndex(Integer targetLessonIndex) {
		this.targetLessonIndex = targetLessonIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.IS_STOP
	 * @return  the value of biz_course_schedule.IS_STOP
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getIsStop() {
		return isStop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.IS_STOP
	 * @param isStop  the value for biz_course_schedule.IS_STOP
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setIsStop(String isStop) {
		this.isStop = isStop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.IS_SIGN
	 * @return  the value of biz_course_schedule.IS_SIGN
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getIsSign() {
		return isSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.IS_SIGN
	 * @param isSign  the value for biz_course_schedule.IS_SIGN
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setIsSign(String isSign) {
		this.isSign = isSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.SIGN_DATE
	 * @return  the value of biz_course_schedule.SIGN_DATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Date getSignDate() {
		return signDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.SIGN_DATE
	 * @param signDate  the value for biz_course_schedule.SIGN_DATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.IS_AUTO_SIGN
	 * @return  the value of biz_course_schedule.IS_AUTO_SIGN
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getIsAutoSign() {
		return isAutoSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.IS_AUTO_SIGN
	 * @param isAutoSign  the value for biz_course_schedule.IS_AUTO_SIGN
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setIsAutoSign(String isAutoSign) {
		this.isAutoSign = isAutoSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.ALLOW_TRANSFER
	 * @return  the value of biz_course_schedule.ALLOW_TRANSFER
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getAllowTransfer() {
		return allowTransfer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.ALLOW_TRANSFER
	 * @param allowTransfer  the value for biz_course_schedule.ALLOW_TRANSFER
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setAllowTransfer(String allowTransfer) {
		this.allowTransfer = allowTransfer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.ALLOW_MULTI
	 * @return  the value of biz_course_schedule.ALLOW_MULTI
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getAllowMulti() {
		return allowMulti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.ALLOW_MULTI
	 * @param allowMulti  the value for biz_course_schedule.ALLOW_MULTI
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setAllowMulti(String allowMulti) {
		this.allowMulti = allowMulti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.RECORD_STATE
	 * @return  the value of biz_course_schedule.RECORD_STATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getRecordState() {
		return recordState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.RECORD_STATE
	 * @param recordState  the value for biz_course_schedule.RECORD_STATE
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setRecordState(String recordState) {
		this.recordState = recordState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.CREATE_USER_ID
	 * @return  the value of biz_course_schedule.CREATE_USER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.CREATE_USER_ID
	 * @param createUserId  the value for biz_course_schedule.CREATE_USER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.CREATE_TIME
	 * @return  the value of biz_course_schedule.CREATE_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.CREATE_TIME
	 * @param createTime  the value for biz_course_schedule.CREATE_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.MODIFY_USER_ID
	 * @return  the value of biz_course_schedule.MODIFY_USER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public String getModifyUserId() {
		return modifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.MODIFY_USER_ID
	 * @param modifyUserId  the value for biz_course_schedule.MODIFY_USER_ID
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_course_schedule.MODIFY_TIME
	 * @return  the value of biz_course_schedule.MODIFY_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_course_schedule.MODIFY_TIME
	 * @param modifyTime  the value for biz_course_schedule.MODIFY_TIME
	 * @mbggenerated  Fri Dec 09 14:40:22 CST 2016
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
}